### ISSUE TITLE
Deactivated gridlines show up on screenshots produced by PhantomJS

### ISSUE THREAD

**Issue by neverfox** [FormidableLabs/victory-axis#72]
It seems that the gridlines are always included in the SVG but can have `stroke:#c9c5bb;fill:none;stroke-width:0;stroke-linecap:round;` by default. The problem is that, for some reason, they still always show up in screen captures made by PhantomJS (we're using webshot). I'm not sure why that is happening, but it could be avoided by simply not rendering those elements, rather than attempting to hide them with styles  (after all, this *is* React, but maybe there's a good reason this approach was taken). Alternatively, we verified that also setting `stroke:none` fixed the issue.

**Comment by boygirl** [comment]
@neverfox how does this sound:

short term: change the default style to `stroke:none`
soon: some `isVisible` util that will not render elements whose styles evaluate to invisible. I think we _do_ want to leave control of element visibility to the `style` prop though, rather than expanding the api surface with stuff like `showGrid`, `showAxisLine`, `showTickLines` etc.

**Comment by neverfox** [comment]
Sounds good to me!
